name: Cypress Tests

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.1'

      - name: Install dependencies
        run: npm ci

      - name: Install additional dependencies
        run: npm install --save-dev @faker-js/faker mochawesome-merge mochawesome-report-generator

      - name: Run Cypress tests
        run: npx cypress run

      - name: Generate test report
        run: npm run generate:report

      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: cypress-test-report
          path: cypress/reports/index.html
